# TODO: disable 404.html, robots.txt, sitemap.xml

base_url = "/"
compile_sass = false
build_search_index = false
output_dir = "build"
minify_html = true
hard_link_static = true

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
